# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../msvc-full-features/stdafx.h \
    ../src/messages.h \
    ../object_creator/creator_main_window.h \
    ../object_creator/dual_list_box.h \
    ../object_creator/fake_spell_listbox.h \
    ../object_creator/fake_spell_window.h \
    ../object_creator/map_viewer.h \
    ../object_creator/spell_window.h
SOURCES += ../msvc-full-features/stdafx.cpp \
    ../src/messages.cpp \
    ../object_creator/creator_main.cpp \
    ../object_creator/creator_main_window.cpp \
    ../object_creator/dual_list_box.cpp \
    ../object_creator/fake_spell_listbox.cpp \
    ../object_creator/fake_spell_window.cpp \
    ../object_creator/map_viewer.cpp \
    ../object_creator/moc_dual_list_box.cpp \
    ../object_creator/moc_fake_spell_listbox.cpp \
    ../object_creator/moc_fake_spell_window.cpp \
    ../object_creator/spell_window.cpp
